### PR TITLE
IBN-748: Cherry-pick the persistence.mapdb bundle

### PR DESCRIPTION
**Pull request by mkhl**
This cherry-picks the [persistence.mapdb bundle](https://github.com/eclipse/smarthome/pull/5419) and the persistence service fixes it requires.

### CODE REVIEW

**Comment by mkhl** [comment]
retest this please

**Comment by kirantpatil** [comment]
Hi @mkhl and @pwolfart,

I have a old ESH running and would like to test "restoreOnStartup" using this binding.

May I know where to download jar file or how to build in my workspace to test it ?

So can I follow configuration setup as mentioned in [docs](https://docs.openhab.org/addons/persistence/mapdb/readme.html) ?

Thanks.

**Comment by mkhl** [comment]
Hi @kirantpatil,

> I have a old ESH running and would like to test "restoreOnStartup" using this binding.

I don’t think that’ll work, old ESH had problems initialising persistence services (see 4632a886b8675e12e132ebf3dfccd2c42bf5b751 and 1987dce496da483ea2c7c177fe98b68748434ec1).

> May I know where to download jar file or how to build in my workspace to test it ?

There’s no download available yet, I’d suggest waiting until this is merged upstream: eclipse/smarthome#5419

You can build it yourself using:

    mvn install -DskipTests=true -DskipChecks=true

(or just `mvn install` to also run the checks and tests)

> So can I follow configuration setup as mentioned in docs ?

Following [the updated docs](https://github.com/AlJungOrg/smarthome/blob/3fe9b2a2d0d4e7674e0069db30af7c3d2747f99d/extensions/persistence/org.eclipse.smarthome.persistence.mapdb/README.md#mapdb-persistence) should work.

**Comment by kirantpatil** [comment]
@mkhl, Thanks a lot. 

We will compile and build by manually copying the code to existing code base and report our findings.

**Comment by kirantpatil** [comment]
Hi @mkhl,

Could you please let us know how to download all commits as patch and apply to our codebase ?

Thanks.

**Comment by kirantpatil** [comment]
Hi @mkhl, just now saw your comment at smarthome project and I will use the upstream ESH code  rather than patching our old ESH.

Thanks.

**Pull request merged**
