### PR TITLE
RRD4J: Only clean up data if the Item is still gone after a delay

### PR DESCRIPTION
**Pull request by mkhl**

### CODE REVIEW

**Review by mkhl — COMMENTED** [review]
I’m still looking into making this service configurable, specifically

* whether it should run at all
* how long it should wait before deleting data

**Comment by pwolfart** [comment]
I'm shure there is a simple reason but I can not imagine why we need to delay the deletion of items at all?

**Comment by mkhl** [comment]
> I'm shure there is a simple reason but I can not imagine why we need to delay the deletion of items at all?

Every time we modify a function, we delete the corresponding Items and recreate them. Without the delay, every save would reset the item’s historical states.

**Comment by pwolfart** [comment]
Oh, why did I ask!?
So as soon as SV-Control starts to work properly this code becomes obsolete!
Wouldn't it be a great to document this in the code?

**Comment by mkhl** [comment]
> Wouldn't it be a great to document this in the code?

Well if I were to fix SV-Control then _I_ wouldn’t think to look in random ESH modules for comments stating that they’re obsolete now…

How about adding that information to a ticket instead? If we have one for simplifying SV-Control saving behaviour we could make it a subtask of that.

**Comment by pwolfart** [comment]
Sounds great, I will create the ticket.

**Pull request merged**
